grails-app/domain/com/mbds/grails/User.groovy
package com.mbds.grails

import groovy.transform.EqualsAndHashCode
import groovy.transform.ToString
import grails.compiler.GrailsCompileStatic

@GrailsCompileStatic
@EqualsAndHashCode(includes='username')
@ToString(includes='username', includeNames=true, includePackage=false)
class User implements Serializable {

    private static final long serialVersionUID = 1

    String username
    String password
    boolean enabled = true
    boolean accountExpired
    boolean accountLocked
    boolean passwordExpired

    static hasMany = [annonces: Annonce]

    Set<Role> getAuthorities() {
        (UserRole.findAllByUser(this) as List<UserRole>)*.role as Set<Role>
    }

    static constraints = {
        password nullable: false, blank: false, password: true
        username nullable: false, blank: false, unique: true
    }

    static mapping = {
	    password column: '`password`'
    }
}

grails-app/controllers/com/mbds/grails/UserController.groovy
package com.mbds.grails

import grails.plugin.springsecurity.SpringSecurityService
import grails.plugin.springsecurity.annotation.Secured
import grails.validation.ValidationException
import static org.springframework.http.HttpStatus.*

@Secured(['ROLE_ADMIN','ROLE_MODO'])
class UserController {

    UserService userService
    SpringSecurityService springSecurityService
    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        respond userService.list(params)
    }

    def show(Long id) {
        respond userService.get(id)
    }

    def create() {

        respond new User(params), model: [roleList:  Role.list()]
    }

    def save(User user) {

        if (user == null) {
            notFound()
            return
        }

        try {

            def userUser = new User(username: params.username, password: params.password ).save()
            def userRole = Role.findByAuthority(params.role)
            UserRole.create(userUser, userRole, true)

        } catch (ValidationException e) {
            respond user.errors, view:'create'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'user.label', default: 'Utilisateyr')])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    def edit(Long id) {

        respond userService.get(id) , model: [roleList:  Role.list()]

    }

    def update() {
        def enabled
        def accountExpired
        def accountLocked
        def passwordExpired
        if(params.enabled == "on"){
             enabled = true
        }
        else {
              enabled = false
        }
        if(params.accountExpired == "on"){
             accountExpired = true
        }
        else {
              accountExpired = false
        }
        if(params.accountLocked == "on"){
             accountLocked = true
        }
        else {
               accountLocked = false
        }
        if(params.passwordExpired == "on"){
             passwordExpired = true
        }
        else {
             passwordExpired = false
        }

        def user = User.get(params.id)
        user.username = params.username
        user.enabled = enabled
        user.accountExpired = accountExpired
        user.accountLocked = accountLocked
        user.passwordExpired = passwordExpired
        def role = Role.get(params.role)
        UserRole.create(user,role,true)

//        user.author = User.get(params.author.id)
        if (user == null) {
            notFound()
            return
        }
        try {
            userService.save(user)

        }
        catch(Exception e){

        }
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'user.label', default: 'Utilisateur'), ""])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    def delete(Long id) {
        if (id == null) {
            notFound()
            return
        }
        try {


            UserRole.removeAll(userService.get(id))
            userService.delete(id)


        } catch (Exception e) {

        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'user.label', default: 'User'), id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'user.label', default: 'User'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/user/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'user.label', default: 'User')}" />
        <title><g:message code="default.create.label" args="[entityName]" /></title>
    </head>
    <body>
    <hr>

        <div id="create-user" class="content scaffold-create" role="main">

            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.user}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.user}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>


            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Ajouter utilisateur</h3>
                </div>

            <g:form controller="user" action="save" method="POST">
                <div class="card-body">
                  <div class="form-group">
                    <label for="username">Username</label>
                    <input name="username" type="text" class="form-control" id="username" placeholder="Username">
                  </div>
                  <div class="form-group">
                    <label for="password">Password</label>
                    <input name="password" type="password" class="form-control" id="password" placeholder="Password">
                  </div>

                    <select name="role" class="form-select" aria-label="Default select example">

                        <g:each in="${roleList}" var="role">

                            <option value="${role.authority}">${role.authority}</option>


                        </g:each>
                    </select>
                </div>


                <div class="card-footer">
                <g:submitButton name="create" class="save btn btn-default" value="${message(code: 'default.button.create.label', default: 'Create')}" />

                </div>
            </g:form>



        </div>
    </body>
</html>

grails-app/views/user/edit.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'user.label', default: 'User')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
    </head>
    <body>

    <hr>
    <g:form controller="user" action="update" id="${user.id}" method="PUT">
        <g:hiddenField name="version" value="${this.user?.version}"/>
        <div class="card-body">
            <div class="form-group">
                <label for="exampleInputEmail1">Nom utilisateur</label>
                <input type="text" class="form-control" id="exampleInputEmail1" name="username" value="${user.username}" placeholder="Enter email">
            </div>
            <div class="form-group">
                <div class="form-check">
                    <g:if test="${user.enabled}">
                        <input class="form-check-input" name="enabled" type="checkbox" v id="flexCheckDefault1" checked>
                    </g:if>
                    <g:else>
                        <input class="form-check-input" name="enabled" type="checkbox"  id="flexCheckDefault1" >
                    </g:else>
                    <label class="form-check-label" for="flexCheckDefault1">
                        Compte Activé
                    </label>
                </div>
            </div>
            <div class="form-group">
                <div class="form-check">
                    <g:if test="${user.accountExpired}">
                        <input class="form-check-input" name="accountExpired"   type="checkbox"  id="flexCheckDefault2" checked>
                    </g:if>
                    <g:else>
                        <input class="form-check-input" name="accountExpired" type="checkbox"  id="flexCheckDefault2" >
                    </g:else>                    <label class="form-check-label" for="flexCheckDefault2">
                        Compte Expiré
                    </label>
                </div>
            </div>
            <div class="form-group">
                <div class="form-check">
                    <g:if test="${user.accountLocked}">
                        <input class="form-check-input" name="accountLocked" type="checkbox"  id="flexCheckDefault3" checked>
                    </g:if>
                    <g:else>
                        <input class="form-check-input" name="accountLocked" type="checkbox" id="flexCheckDefault3" >
                    </g:else>                    <label class="form-check-label" for="flexCheckDefault3">
                        Compte Bloqué
                    </label>
                </div>
            </div>
            <div class="form-group">
                <div class="form-check">
                    <g:if test="${user.passwordExpired}">
                        <input class="form-check-input" name="passwordExpired" type="checkbox"  id="flexCheckDefault4" checked>
                    </g:if>
                    <g:else>
                        <input class="form-check-input" name="passwordExpired" type="checkbox"  id="flexCheckDefault4" >
                    </g:else>                    <label class="form-check-label" for="flexCheckDefault4">
                        Mot de passe expiré
                    </label>
                </div>
            </div>
            <div class="form-group">
                <select class="form-select" name="role" aria-label="Default select example">
                    <option value="${user.getAuthorities().first().id}" selected>${user.getAuthorities().first().authority}</option>
                    <g:each in="${roleList}" var="role">
                        <g:if test="${role!=user.getAuthorities().first()}">
                            <option value="${role.id}">${role.authority}</option>
                        </g:if>

                        </g:each>
                        </select>
                    </div>
                </div>
                <!-- /.card-body -->

        <div class="card-footer">
            <button type="submit" class="btn btn-primary">Valider</button>
        </div>
    </g:form>
        </div>


    </body>
</html>

grails-app/views/user/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'user.label', default: 'User')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
<body>
<hr>

<div class="card">

    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Liste des Utilisateurs</h3>
            <g:if test='${flash.message}'>
                <div class="alert alert-danger" role="alert">${flash.message}</div>
            </g:if>
        </div>
            <!-- /.card-header -->
            <div class="card-body">

        <g:if test='${flash.message}'>
            <div class="alert alert-default-info" role="alert">${flash.message}</div>
        </g:if>

                <div id="example1_wrapper" class="dataTables_wrapper dt-bootstrap4"><div class="row"><div class="col-sm-12">
                    <table id="example1" class="table table-bordered dataTable dtr-inline" role="grid" aria-describedby="example1_info">
                        <thead>
                        <tr role="row"><th class="sorting sorting_asc" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Rendering engine: activate to sort column descending">Id</th><th class="sorting sorting_asc" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Rendering engine: activate to sort column descending">Nom Utilisateur</th><th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending">Mot de passe expiré</th><th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="Platform(s): activate to sort column ascending">Compte bloqué</th><th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="Engine version: activate to sort column ascending">Compte expiré</th><th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">Activé</th><th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">Modifier</th><th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">Supprimer</th></tr>
                        </thead>
                        <tbody>

                        <g:each in="${userList}" var="utilisateur">
                            <tr class="">
                                <td class="dtr-control sorting_1" tabindex="0">${utilisateur.id}</td>
                                <td class="" tabindex="0">${utilisateur.username}</td>
                                <td>${utilisateur.passwordExpired}</td>
                                <td>${utilisateur.accountLocked}</td>
                                <td>${utilisateur.accountExpired}</td>
                                <td>${utilisateur.enabled}</td>
                                <td>
                                    <g:link id="${utilisateur.id}" action="edit">
                                        <input type="button"  class="btn btn-warning" value="Modifier" class="button"/>
                                    </g:link>
                                </td>
                                <td>


                                    <button type="button" id="button_${utilisateur.id}" class="btn btn-danger" data-toggle="modal" data-target="#delete_${utilisateur.id}" data-whatever="@mdo">Supprimer</button>

                                </td>

                                <!-- /.modale start delete -->
                                <div class="modal fade" id="delete_${utilisateur.id}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
                                    <div class="modal-dialog modal-dialog-centered" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h4 id="exampleModalLabel1">Vous voulez vraiment suprimer ${utilisateur.username} de cette utilisateur ? </h4>
                                            </div>

                                            <div class="modal-body">

                                                <g:form controller="user" id="${utilisateur.id}" action="delete" method="DELETE">
                                                    <input type="submit" class="btn btn-success" value="Oui" />
                                                </g:form>



                                                <button type="button" class="btn btn-danger" data-dismiss="modal" aria-label="Close">Non</button>

                                            </div>

                                        </div>


                                    </div>
                                </div>
                                <!-- /.modale end delete -->

                            </tr>



                        </g:each>
                        </tbody>

                    </table>
            </div>
            <!-- /.card-body -->
        </div>
    </div>


<g:javascript>
    $(document).ready( function () {
        $('#example1').DataTable();
    } );
</g:javascript>
</body>
</html>

grails-app/views/user/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'user.label', default: 'User')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0"><g:message code="default.show.label" args="[entityName]" /></h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active"><g:message code="default.show.label" args="[entityName]" /></li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
        <a href="#show-user" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="show-user" class="content scaffold-show" role="main">
            <h1><g:message code="default.show.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:display bean="user" />
            <g:form resource="${this.user}" method="DELETE">
                <fieldset class="buttons">
                    <g:link class="edit" action="edit" resource="${this.user}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                    <input class="delete" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>